# Generated by Django 5.0.6 on 2024-05-16 20:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)])),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30)])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)])),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(100)])),
                ('role', models.IntegerField(choices=[(8, 'Admin'), (9, 'User')])),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='VacationsModel',
            fields=[
                ('vacation_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacation_description', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000), django.core.validators.MinLengthValidator(2)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_file_name', models.ImageField(upload_to='static/images/vacations')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
            options={
                'db_table': 'vacations',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel')),
                ('vacation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_likes', to='api.vacationsmodel')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
    ]
