# Generated by Django 5.0.6 on 2024-05-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_like_vacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationsmodel',
            name='likes_count',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
